version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.1
  helm: circleci/helm@2.0.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/gcp:2022.09
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/crunchyroll/ctp-gke-example-ts/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  helm-deployment:
    environment:
      DOCKER_REPO: gcp-node-test
      IMAGE_NAME: web-nodejs-image
      IMAGE_NAME_2: api-nodejs-image
      HELM_RELEASE_NAME: nodejs
      VERSION_PREFIX: 0.1
      CHART_NAME: circle-nodejs-chart
      GCP_PROJECT: peak-apparatus-379619
      GKE_CLUSTER: gke-test-us-central1
      GKE_REGION: us-central1
    executor: my-custom-executor
    steps:
      - gcp-cli/initialize
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - helm/install-helm-client
      - add_ssh_keys:
          fingerprints:
            - "d8:7b:76:af:9d:b0:ba:06:6d:38:7d:a4:7f:83:c3:fd"
      - run:
          name: Setup Env Variables
          command: |
            echo 'export TAG="${VERSION_PREFIX}.${CIRCLE_BUILD_NUM}"' >> "$BASH_ENV"
            # echo 'export TAG_2="${VERSION_PREFIX}.${CIRCLE_BUILD_NUM}"' >> "$BASH_ENV"
            echo 'export RELEASE_NAME="${HELM_RELEASE_NAME}"' >> "$BASH_ENV"
            echo 'export CHART_NAME="${CHART_NAME}"' >> "$BASH_ENV"
            echo 'export CHART_REPO_NAME="${CIRCLE_PROJECT_REPONAME}"' >> "$BASH_ENV"
      - run:
          name: Update Helm Chart
          command: |
            git clone "https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git"
            git -C /home/circleci/project/$CIRCLE_PROJECT_REPONAME checkout $CIRCLE_BRANCH
            git -C /home/circleci/project/$CIRCLE_PROJECT_REPONAME config --global user.email "argsharma01@gmail.com"
            git -C /home/circleci/project/$CIRCLE_PROJECT_REPONAME config --global user.name "$CIRCLE_JOB"
            yq -i '.version=strenv(TAG)' /home/circleci/project/$CIRCLE_PROJECT_REPONAME/charts/$CHART_NAME/Chart.yaml
            yq -i '.appVersion=strenv(TAG)' /home/circleci/project/$CIRCLE_PROJECT_REPONAME/charts/$CHART_NAME/Chart.yaml
            git -C /home/circleci/project/$CIRCLE_PROJECT_REPONAME add .
            git -C /home/circleci/project/$CIRCLE_PROJECT_REPONAME commit -m "[skip ci] Helm chart version update"
            git -C /home/circleci/project/$CIRCLE_PROJECT_REPONAME push
  build-image:
    environment:
      DOCKER_REPO: gcp-node-test
      IMAGE_NAME: web-nodejs-image
      IMAGE_NAME_2: api-nodejs-image
      VERSION_PREFIX: 0.1
      GCP_PROJECT: peak-apparatus-379619
      GKE_CLUSTER: gke-test-us-central1
      GKE_REGION: us-central1
    executor: my-custom-executor
    steps:
      - gcp-cli/initialize
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - helm/install-helm-client
      - add_ssh_keys:
          fingerprints:
            - "d8:7b:76:af:9d:b0:ba:06:6d:38:7d:a4:7f:83:c3:fd"
      - run:
          name: Setup Env Variables
          command: |
            echo 'export TAG="${VERSION_PREFIX}.${CIRCLE_BUILD_NUM}"' >> "$BASH_ENV"
            echo 'export TAG_2="${VERSION_PREFIX}.${CIRCLE_BUILD_NUM}"' >> "$BASH_ENV"
            echo 'export RELEASE_NAME="${HELM_RELEASE_NAME}"' >> "$BASH_ENV"
            echo 'export CHART_NAME="${CHART_NAME}"' >> "$BASH_ENV"
            echo 'export CHART_REPO_NAME="${CIRCLE_PROJECT_REPONAME}"' >> "$BASH_ENV"      
      - run:
          name: Build and push container image
          command: |
            gcloud auth configure-docker us-central1-docker.pkg.dev
            cd /home/circleci/project/api/
            docker build -f /home/circleci/project/api/Dockerfile --no-cache --progress=plain -t us-central1-docker.pkg.dev/$GCP_PROJECT/$DOCKER_REPO/$IMAGE_NAME:latest -t us-central1-docker.pkg.dev/$GCP_PROJECT/$DOCKER_REPO/$IMAGE_NAME:$TAG .
            docker push us-central1-docker.pkg.dev/$GCP_PROJECT/$DOCKER_REPO/$IMAGE_NAME:$TAG
            docker push us-central1-docker.pkg.dev/$GCP_PROJECT/$DOCKER_REPO/$IMAGE_NAME:latest
      - run:
          name: Build and push container image 2
          command: |
            gcloud auth configure-docker us-central1-docker.pkg.dev
            cd /home/circleci/project/api/
            docker build -f /home/circleci/project/web/Dockerfile --no-cache --progress=plain -t us-central1-docker.pkg.dev/$GCP_PROJECT/$DOCKER_REPO/$IMAGE_NAME_2:latest -t us-central1-docker.pkg.dev/$GCP_PROJECT/$DOCKER_REPO/$IMAGE_NAME_2:$TAG_2 .
            docker push us-central1-docker.pkg.dev/$GCP_PROJECT/$DOCKER_REPO/$IMAGE_NAME_2:$TAG_2
            docker push us-central1-docker.pkg.dev/$GCP_PROJECT/$DOCKER_REPO/$IMAGE_NAME_2:latest
  deploy-to-kubernetes:
    # circleci_ip_ranges: true
    environment:
      DOCKER_REPO: gcp-node-test
      IMAGE_NAME: web-nodejs-image
      HELM_RELEASE_NAME: nodejs
      CHART_NAME: circle-nodejs-chart
      VERSION_PREFIX: 0.1
      GCP_PROJECT: peak-apparatus-379619
      GKE_CLUSTER: gke-test-us-central1
      GKE_REGION: us-central1
    executor: my-custom-executor
    steps:
      - gcp-cli/initialize
      - checkout
      - helm/install-helm-client
      - add_ssh_keys:
          fingerprints: 
            - "d8:7b:76:af:9d:b0:ba:06:6d:38:7d:a4:7f:83:c3:fd"
      - run:     
          name: Setup Env Variables
          command: |
            echo 'export TAG="${VERSION_PREFIX}.${CIRCLE_BUILD_NUM}"' >> "$BASH_ENV"
            echo 'export TAG_2="${VERSION_PREFIX}.${CIRCLE_BUILD_NUM}"' >> "$BASH_ENV"
            echo 'export RELEASE_NAME="${HELM_RELEASE_NAME}"' >> "$BASH_ENV"
            echo 'export CHART_NAME="${CHART_NAME}"' >> "$BASH_ENV"
            echo 'export CHART_REPO_NAME="${CIRCLE_PROJECT_REPONAME}"' >> "$BASH_ENV"      
      - run:
          name: Connect to Kubernetes Cluster
          command: |
            gcloud auth configure-docker us-central1-docker.pkg.dev
            gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $GCP_PROJECT
      - helm/install-helm-chart:
          add-repo: https://${GH_TOKEN}@raw.githubusercontent.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH/charts/$CHART_NAME
          release-name: $RELEASE_NAME
          chart: /home/circlecli/project/test-nodejs/charts/circle-nodejs-chart/      
      # - run:
      #     name: Install/Update Helm Deployment
      #     command: |
      #       git clone "https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git"
      #       git -C /home/circleci/project/$CIRCLE_PROJECT_REPONAME checkout $CIRCLE_BRANCH
      #       helm install $RELEASE_NAME /home/circleci/project/$CHART_REPO_NAME/charts/$CHART_NAME/ -f /home/circleci/project/$CHART_REPO_NAME/charts/$CHART_NAME/values.yaml --set postRender=""

workflows:
  my-custom-workflow:
    jobs:
      - helm-deployment
      - build-image:
          requires:
            - helm-deployment
      - deploy-to-kubernetes:
          requires:
            - build-image

#test20