apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      {{- range .Values.containers }}
      - name: {{ .name }}
        image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
        command: {{ .command }}
        ports:               
        - containerPort: {{ .containerPort }}
      {{- end }}
