apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
  annotations: 
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /web
        backend:
          serviceName: nodejs-web-app
          servicePort: 80
      - path: /api
        backend:
          serviceName: nodejs-api-app
          servicePort: 80