---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: nodejs-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: nodejs-api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP