# {{- if .Values.serviceAccount.create -}}
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: {{ include "circle-nodejs-chart.serviceAccountName" . }}
#   labels:
#     {{- include "circle-nodejs-chart.labels" . | nindent 4 }}
#   {{- with .Values.serviceAccount.annotations }}
#   annotations:
#     {{- toYaml . | nindent 4 }}
#   {{- end }}
# {{- end }}
