---

apiVersion: v1
kind: Service
metadata:
  name: web-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"my-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: nodejs-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31866
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: nodejs-api-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort