# values for deployment1

deployment1:
  replicas: 1
  image: us-central1-docker.pkg.dev/peak-apparatus-379619/gcp-node-test/web-nodejs-image
  env:
    - name: PORT
      value: "80"
    - name: API_HOST
      value: "api.local"
  containerPort: 80

deployment2:
  replicas: 1
  image: us-central1-docker.pkg.dev/peak-apparatus-379619/gcp-node-test/api-nodejs-image
  env:
    - name: PORT
      value: "8080"
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: gke-cloud-sql-secrets
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: gke-cloud-sql-secrets
          key: password
    - name: DB
      value: postgres://$(DB_USER):$(DB_PASSWORD)@/private-instance-3f6dd53c?jost=/cloudsql/peak-apparatus-379619:us-central1:private-instance-3f6dd53c       
    - name: DB_HOST
      value: "10.65.0.3"
    - name: DB_PORT
      value: "5432"
  containerPort: 8080
serviceAccount:
  create: false
ingress:
  enabled: false
imagePullSecrets: []
nameOverride: "circleci-nodejs-chart-app"
fullnameOverride: "circleci-nodejs-chart"

serviceName: nodejs-service
service:
  type: NodePort
port: 80
